spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: root
    password: root
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true